'use client';

import { Toaster } from '@/components/ui/sonner';
import store from '@/store';
import { Geist, Geist_Mono } from 'next/font/google';
import { Provider } from 'react-redux';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Provider store={store}>
          <QueryClientProvider client={queryClient}>
          <div className="flex h-screen overflow-hidden">
            <Sidebar />
            <div className="flex flex-col flex-1 overflow-hidden">
              <Header />
              <main className="flex-1 overflow-auto bg-gray-100 p-8"> */}
        {/* <ClientWrapper>{children}</ClientWrapper> */}
        <Provider store={store}>
          {children}
          <Toaster duration={5000} position="top-right" />
        </Provider>

        {/* {children} */}
        {/* </main>
            </div>
          </div>
          </QueryClientProvider>
        </Provider> */}
      </body>
    </html>
  );
}
